[package]
edition = "2021"
name = "vortexjs_discovery"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.0.0-beta.0", default-features = false, features = [
    "napi10",
    "experimental",
] }
napi-derive = "3.0.0-beta.0"
oxc = { features = ["semantic", "codegen"], version = "0.72.3" }
oxc_traverse = "0.72.3"
rand = "0.9.1"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
strip = "symbols"
